import 'package:test/test.dart';
import 'package:stability_api/stability_api.dart';

// tests for ChatCompletionResponseMessage
void main() {
  final instance = ChatCompletionResponseMessageBuilder();
  // TODO add properties to the builder and call build()

  group(ChatCompletionResponseMessage, () {
    // The role of the author of this message.
    // String role
    test('to test the property `role`', () async {
      // TODO
    });

    // The contents of the message.
    // String content
    test('to test the property `content`', () async {
      // TODO
    });

    // The tool calls generated by the model, such as function calls.
    // BuiltList<ChatCompletionMessageToolCall> toolCalls
    test('to test the property `toolCalls`', () async {
      // TODO
    });
  });
}
