//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_collection/built_collection.dart';
import 'package:stability_api/src/model/chat_completion_message_tool_call.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'chat_completion_response_message.g.dart';

/// ChatCompletionResponseMessage
///
/// Properties:
/// * [role] - The role of the author of this message.
/// * [content] - The contents of the message.
/// * [toolCalls] - The tool calls generated by the model, such as function calls.
@BuiltValue()
abstract class ChatCompletionResponseMessage
    implements
        Built<ChatCompletionResponseMessage,
            ChatCompletionResponseMessageBuilder> {
  /// The role of the author of this message.
  @BuiltValueField(wireName: r'role')
  ChatCompletionResponseMessageRoleEnum get role;
  // enum roleEnum {  system,  user,  assistant,  };

  /// The contents of the message.
  @BuiltValueField(wireName: r'content')
  String? get content;

  /// The tool calls generated by the model, such as function calls.
  @BuiltValueField(wireName: r'tool_calls')
  BuiltList<ChatCompletionMessageToolCall>? get toolCalls;

  ChatCompletionResponseMessage._();

  factory ChatCompletionResponseMessage(
          [void updates(ChatCompletionResponseMessageBuilder b)]) =
      _$ChatCompletionResponseMessage;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(ChatCompletionResponseMessageBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<ChatCompletionResponseMessage> get serializer =>
      _$ChatCompletionResponseMessageSerializer();
}

class _$ChatCompletionResponseMessageSerializer
    implements PrimitiveSerializer<ChatCompletionResponseMessage> {
  @override
  final Iterable<Type> types = const [
    ChatCompletionResponseMessage,
    _$ChatCompletionResponseMessage
  ];

  @override
  final String wireName = r'ChatCompletionResponseMessage';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    ChatCompletionResponseMessage object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'role';
    yield serializers.serialize(
      object.role,
      specifiedType: const FullType(ChatCompletionResponseMessageRoleEnum),
    );
    if (object.content != null) {
      yield r'content';
      yield serializers.serialize(
        object.content,
        specifiedType: const FullType.nullable(String),
      );
    }
    if (object.toolCalls != null) {
      yield r'tool_calls';
      yield serializers.serialize(
        object.toolCalls,
        specifiedType: const FullType(
            BuiltList, [FullType(ChatCompletionMessageToolCall)]),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    ChatCompletionResponseMessage object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object,
            specifiedType: specifiedType)
        .toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required ChatCompletionResponseMessageBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'role':
          final valueDes = serializers.deserialize(
            value,
            specifiedType:
                const FullType(ChatCompletionResponseMessageRoleEnum),
          ) as ChatCompletionResponseMessageRoleEnum;
          result.role = valueDes;
          break;
        case r'content':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.content = valueDes;
          break;
        case r'tool_calls':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(
                BuiltList, [FullType(ChatCompletionMessageToolCall)]),
          ) as BuiltList<ChatCompletionMessageToolCall>;
          result.toolCalls.replace(valueDes);
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  ChatCompletionResponseMessage deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = ChatCompletionResponseMessageBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

class ChatCompletionResponseMessageRoleEnum extends EnumClass {
  /// The role of the author of this message.
  @BuiltValueEnumConst(wireName: r'system')
  static const ChatCompletionResponseMessageRoleEnum system =
      _$chatCompletionResponseMessageRoleEnum_system;

  /// The role of the author of this message.
  @BuiltValueEnumConst(wireName: r'user')
  static const ChatCompletionResponseMessageRoleEnum user =
      _$chatCompletionResponseMessageRoleEnum_user;

  /// The role of the author of this message.
  @BuiltValueEnumConst(wireName: r'assistant', fallback: true)
  static const ChatCompletionResponseMessageRoleEnum assistant =
      _$chatCompletionResponseMessageRoleEnum_assistant;

  static Serializer<ChatCompletionResponseMessageRoleEnum> get serializer =>
      _$chatCompletionResponseMessageRoleEnumSerializer;

  const ChatCompletionResponseMessageRoleEnum._(String name) : super(name);

  static BuiltSet<ChatCompletionResponseMessageRoleEnum> get values =>
      _$chatCompletionResponseMessageRoleEnumValues;
  static ChatCompletionResponseMessageRoleEnum valueOf(String name) =>
      _$chatCompletionResponseMessageRoleEnumValueOf(name);
}
